apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
    spec:
      containers:
      - name: sentiment-api
        image: 865698115856.dkr.ecr.ap-south-1.amazonaws.com/custom-images:sentiment-api
        ports:
        - containerPort: 5000