apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-ui
  template:
    metadata:
      labels:
        app: sentiment-ui
    spec:
      containers:
      - name: sentiment-ui
        image: <your-ecr-repo>/sentiment-ui:latest
        ports:
        - containerPort: 3000